title: Terminal Root
email: contact@terminalroot.com
author: 'Marcos Oliveira'
description: >- # this means to ignore newlines until "baseurl:"
  A little much about C++, Operating Systems, Programming and Web Development
baseurl: "/" 
twitter_username: marcoscplusplus
github_username:  terroo

url: "https://terminalroot.com"
# gem install kramdown rouge
# http://jwarby.github.io/jekyll-pygments-themes/languages/javascript.html
disqus:
  shortname: terroo
#theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html

plugins:
  - jekyll-feed
exclude:
  - README.md
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png
include: ['_pages']
permalink: /:title/
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About
    url: /about
  - title: Newsletter
    url: /newsletter
