# Site settings
title: 'Terminal Root'
subtitle: 'A little much about C++, Game Development, Programming and Web.'
email: fake@terminalroot.com
author: 'Marcos Oliveira'
description: > # this means to ignore newlines until "baseurl:"
  A little much about C++, Game Development, Programming and Web.

twitter_username: TerminalRootTV
github_username:  terroo
gitlab_username:  TerminalRoot
youtube_username:  TerminalRootTV
#
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
#    css_class   : 'syntax'


permalink: /:year/:month/:title/
#
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Newsletter
    url: /newsletter
  - title: Tags
    url: /tags
  - title: Blog
    url: /blog
