title: Terminal Root # your site title
author: Marcos Oliveira
email: marcos@terminalroot.com.br # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  GNU/Linux site, Software Development, Gentoo, BSD, Open Source and Free Software.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://terroo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TerminalRootTV # replace with your_twitter_username or comment to remove link from footer
github_username:  terroo # replace with your_github_username or comment to remove link from footer
instagram_username: terminalroot # replace with your_instagram_username or comment to remove link from footer
social:
  name: Terminal Root
  links:
    - https://twitter.com/TerminalRootTV
    - https://www.facebook.com/TerminalRootTV
    - https://www.linkedin.com/in/TerminalRootTV
    - https://plus.google.com/+TerminalRootTV
    - https://github.com/terroo
    - https://keybase.io/TerminalRootTV

disqus:
  shortname: terroo # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
